export const UPDATE_USER = "UPDATE_USER_DETAILS";
export const UPDATE_INST = "UPDATE_INST_DETAILS";
export const UPDATE_EVENTS = "UPDATE_EVENT_DETAILS";
export const SET_SELECTED_EVENT = "SET_SELECTED_EVENT";
export const LOGOUT_USER = "CLEAR_ALL";
